# Generated by Django 4.1.4 on 2023-02-10 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rechnung_strasse', models.CharField(max_length=255)),
                ('rechnung_nr', models.CharField(max_length=255)),
                ('rechnung_ort', models.CharField(max_length=255)),
                ('rechnung_land', django_countries.fields.CountryField(max_length=2)),
                ('rechnung_plz', models.CharField(max_length=255)),
                ('address_type', models.CharField(choices=[('B', 'Rechnungsadresse'), ('S', 'Lieferadresse')], max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rechnungsadresse',
                'verbose_name_plural': 'Rechnungsadressen',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('categorypic', models.ImageField(blank=True, null=True, upload_to='produktbilder/')),
            ],
            options={
                'verbose_name': 'Kategorie',
                'verbose_name_plural': 'Kategorien',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=255)),
                ('preis', models.FloatField()),
                ('preis2', models.FloatField(blank=True, null=True)),
                ('preis3', models.FloatField(blank=True, null=True)),
                ('preis4', models.FloatField(blank=True, null=True)),
                ('preis5', models.FloatField(blank=True, null=True)),
                ('preis6', models.FloatField(blank=True, null=True)),
                ('preis7', models.FloatField(blank=True, null=True)),
                ('kurzbeschreibung', models.CharField(default='', max_length=500)),
                ('beschreibung', models.CharField(default='', max_length=500)),
                ('lieferung', models.CharField(blank=True, default='ca. 5 bis 7 Tage', max_length=255, null=True)),
                ('montage', models.CharField(blank=True, max_length=255, null=True)),
                ('titelbild', models.ImageField(blank=True, null=True, upload_to='produktbilder/')),
                ('slug', models.SlugField(max_length=255)),
                ('artikelnr', models.CharField(max_length=255)),
                ('farbe', models.CharField(blank=True, max_length=255, null=True)),
                ('nut', models.CharField(blank=True, max_length=255, null=True)),
                ('falz', models.CharField(blank=True, max_length=255, null=True)),
                ('falzluft', models.CharField(blank=True, max_length=255, null=True)),
                ('fuge', models.CharField(blank=True, max_length=255, null=True)),
                ('glasdicke', models.CharField(blank=True, max_length=255, null=True)),
                ('material', models.CharField(blank=True, max_length=255, null=True)),
                ('hersteller', models.CharField(blank=True, max_length=255, null=True)),
                ('sortierung', models.IntegerField(blank=True, null=True)),
                ('kategorie', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.category')),
            ],
            options={
                'verbose_name': 'Produkte',
                'verbose_name_plural': 'Produkte',
                'ordering': ['sortierung'],
            },
        ),
        migrations.CreateModel(
            name='MP_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
            ],
            options={
                'verbose_name': 'MP_Kategorie',
                'verbose_name_plural': 'MP_Kategorien',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ShippingCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_from', models.FloatField(blank=True, null=True)),
                ('price_to', models.FloatField(blank=True, null=True)),
                ('shipping_price', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(max_length=255)),
                ('sub_slug', models.SlugField(max_length=255)),
            ],
            options={
                'verbose_name': 'Subkategorie',
                'verbose_name_plural': 'Subkategorien',
                'ordering': ['sub_name'],
            },
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lieferung_strasse', models.CharField(max_length=255)),
                ('lieferung_nr', models.CharField(max_length=255)),
                ('lieferung_ort', models.CharField(max_length=255)),
                ('lieferung_land', django_countries.fields.CountryField(max_length=2)),
                ('lieferung_plz', models.CharField(max_length=255)),
                ('address_type', models.CharField(choices=[('B', 'Rechnungsadresse'), ('S', 'Lieferadresse')], max_length=500)),
                ('vorname', models.CharField(blank=True, max_length=255, null=True)),
                ('nachname', models.CharField(blank=True, max_length=255, null=True)),
                ('firmenname', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_address', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lieferadresse',
                'verbose_name_plural': 'Lieferadressen',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=1)),
                ('aussenbreite', models.IntegerField(blank=True, default=250, null=True)),
                ('aussenhöhe', models.IntegerField(blank=True, default=250, null=True)),
                ('element', models.IntegerField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('ordered_date', models.DateTimeField()),
                ('ordered', models.BooleanField(default=False)),
                ('payment', models.BooleanField(default=False)),
                ('payment_method', models.CharField(choices=[('R', 'Rechnung*'), ('V', 'Vorkasse (2% Skonto)')], default='R', max_length=255)),
                ('shippingcost', models.FloatField(blank=True, default=0, null=True)),
                ('discount', models.FloatField(blank=True, null=True)),
                ('discount_pct', models.FloatField(blank=True, null=True)),
                ('skonto', models.FloatField(blank=True, null=True)),
                ('pre_total', models.FloatField(blank=True, null=True)),
                ('order_mwst', models.FloatField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
                ('billing_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_address', to='store.address')),
                ('items', models.ManyToManyField(to='store.orderitem')),
                ('shipping_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_address', to='store.shippingaddress')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bestellung',
                'verbose_name_plural': 'Bestellungen',
                'ordering': ['-ordered_date'],
            },
        ),
        migrations.CreateModel(
            name='Marketplace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('price', models.FloatField(blank=True, null=True)),
                ('description', models.CharField(default='', max_length=255)),
                ('condition', models.CharField(choices=[('G', 'Gebraucht'), ('N', 'Neu')], default='G', max_length=255)),
                ('place', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='inserate/')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='inserate/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='inserate/')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('payment', models.BooleanField(default=False)),
                ('tid', models.IntegerField(blank=True, null=True)),
                ('numberof', models.IntegerField(blank=True, null=True)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('typ_marke', models.CharField(blank=True, max_length=255, null=True)),
                ('anonym', models.CharField(choices=[('Ja', 'Ja'), ('Nein', 'Nein')], default='Ja', max_length=255)),
                ('category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mp_category', to='store.mp_category')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Marketplace',
                'verbose_name_plural': 'Marketplaces',
                'ordering': ['-add_date'],
            },
        ),
        migrations.CreateModel(
            name='Marke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('markepic', models.ImageField(blank=True, null=True, upload_to='markebilder/')),
                ('marketext', models.TextField(blank=True)),
                ('item', models.ManyToManyField(blank=True, related_name='item_marken', to='store.item')),
            ],
            options={
                'verbose_name': 'Marke',
                'verbose_name_plural': 'Marken',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Kunde',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firmenname', models.CharField(blank=True, max_length=255, null=True)),
                ('rabatt', models.FloatField(blank=True, null=True)),
                ('newsletter', models.BooleanField(blank=True, null=True)),
                ('mobile', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('birthday', models.CharField(blank=True, max_length=255, null=True)),
                ('interne_nummer', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kunde',
                'verbose_name_plural': 'Kunden',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='item',
            name='subkategorie',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.subcategory'),
        ),
        migrations.CreateModel(
            name='Elemente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elementnr', models.IntegerField(blank=True, null=True)),
                ('kuehlposition', models.CharField(max_length=255)),
                ('bemerkung', models.CharField(max_length=255)),
                ('aussenbreite', models.IntegerField(blank=True, null=True)),
                ('aussenhöhe', models.IntegerField(blank=True, null=True)),
                ('dichtungen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.item')),
                ('kunde', models.ManyToManyField(blank=True, related_name='kunden_elemente', to='store.kunde')),
            ],
            options={
                'verbose_name': 'Element',
                'verbose_name_plural': 'Elemente',
                'ordering': ['elementnr'],
            },
        ),
    ]
