# Generated by Django 4.1.4 on 2023-02-28 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0005_marketplace_anonym_ins_marketplace_marke_ins_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MP_JobsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
            ],
            options={
                'verbose_name': 'MP_JobsKategorie',
                'verbose_name_plural': 'MP_JobsKategorien',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='JobsMarketplace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('jobdescription', models.CharField(default='', max_length=255)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('payment', models.BooleanField(default=False)),
                ('tid', models.IntegerField(blank=True, null=True)),
                ('requirements', models.CharField(default='', max_length=255)),
                ('language', models.CharField(default='', max_length=255)),
                ('res_description', models.CharField(default='', max_length=255)),
                ('contact_person', models.CharField(default='', max_length=255)),
                ('category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mp_jobscategory', to='store.mp_jobscategory')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'JobMarketplace',
                'verbose_name_plural': 'JobMarketplaces',
                'ordering': ['-add_date'],
            },
        ),
    ]
