# Generated by Django 4.1.4 on 2023-03-09 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_mp_jobscategory_jobsmarketplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsmarketplace',
            name='place',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='jobsmarketplace',
            name='jobdescription',
            field=models.CharField(default='', max_length=500),
        ),
    ]
