# Generated by Django 4.1.4 on 2023-03-09 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_jobsmarketplace_place_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsmarketplace',
            name='datejob',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='jobsmarketplace',
            name='kindof',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='jobsmarketplace',
            name='pensum',
            field=models.CharField(default='', max_length=255),
        ),
    ]
