# Generated by Django 4.1.4 on 2023-03-09 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_jobsmarketplace_datejob_jobsmarketplace_kindof_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsmarketplace',
            name='check_portal',
            field=models.CharField(default='Jobs', max_length=255),
        ),
    ]
