# Generated by Django 4.1.4 on 2023-03-10 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_jobsmarketplace_check_portal'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsmarketplace',
            name='region',
            field=models.CharField(default='', max_length=255),
        ),
    ]
