# Generated by Django 4.1.4 on 2023-03-13 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_jobsmarketplace_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsmarketplace',
            name='jobdescription',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='jobsmarketplace',
            name='region',
            field=models.CharField(choices=[(' Aargau', ' Aargau'), (' Appenzell Innerrhoden', ' Appenzell Innerrhoden'), (' Appenzell Ausserrhoden', ' Appenzell Ausserrhoden'), (' Bern', ' Bern'), (' Basel-Landschaft', ' Basel-Landschaft'), (' Basel-Stadt', ' Basel-Stadt'), (' Freiburg', ' Freiburg'), (' Genf', ' Genf'), (' Glarus', ' Glarus'), (' Graubünden', ' Graubünden'), (' Jura', ' Jura'), (' Luzern', ' Luzern'), (' Neuenburg', ' Neuenburg'), (' Nidwalden', ' Nidwalden'), (' Obwalden', ' Obwalden'), (' St. Gallen', ' St. Gallen'), (' Schaffhausen', ' Schaffhausen'), (' Solothurn', ' Solothurn'), (' Schwyz', ' Schwyz'), (' Thurgau', ' Thurgau'), (' Tessin', ' Tessin'), (' Uri', ' Uri'), (' Waadt', ' Waadt'), (' Wallis', ' Wallis'), (' Zug', ' Zug'), (' Zürich', ' Zürich')], default='Zürich', max_length=255),
        ),
        migrations.AlterField(
            model_name='jobsmarketplace',
            name='requirements',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
