# Generated by Django 4.1.4 on 2023-04-20 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_jobsmarketplace_jobdescription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elemente',
            name='dichtungen',
        ),
        migrations.RemoveField(
            model_name='elemente',
            name='kunde',
        ),
        migrations.RemoveField(
            model_name='item',
            name='kategorie',
        ),
        migrations.RemoveField(
            model_name='item',
            name='subkategorie',
        ),
        migrations.RemoveField(
            model_name='marke',
            name='item',
        ),
        migrations.RemoveField(
            model_name='order',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='user',
        ),
        migrations.DeleteModel(
            name='ShippingCost',
        ),
        migrations.DeleteModel(
            name='Elemente',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Marke',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
